CREATE TABLE IF NOT EXISTS sal_craft_recipes (
  id VARCHAR(100) NOT NULL,
  data LONGTEXT,
  updatedAt TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS sal_craft_categories (
  id VARCHAR(100) NOT NULL,
  data LONGTEXT,
  updatedAt TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS sal_craft_blueprints (
  id VARCHAR(100) NOT NULL,
  data LONGTEXT,
  updatedAt TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS sal_craft_bench_types (
  id VARCHAR(100) NOT NULL,
  data LONGTEXT,
  updatedAt TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS sal_craft_bench_locations (
  id VARCHAR(100) NOT NULL,
  data LONGTEXT,
  updatedAt TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS sal_craft_player_progress (
  identifier VARCHAR(100) NOT NULL,
  xp INT NOT NULL DEFAULT 0,
  updatedAt TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (identifier)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS sal_craft_player_blueprints (
  identifier VARCHAR(100) NOT NULL,
  blueprintId VARCHAR(100) NOT NULL,
  learnedAt TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (identifier, blueprintId)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS sal_craft_queue (
  id INT NOT NULL AUTO_INCREMENT,
  identifier VARCHAR(100) NOT NULL,
  recipeId VARCHAR(100) NOT NULL,
  amount INT NOT NULL DEFAULT 1,
  benchType VARCHAR(100) NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'queued',
  startedAt INT NOT NULL,
  endAt INT NOT NULL,
  payload LONGTEXT,
  updatedAt TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
